POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbG1hayIsImlkIjoiNjE2ZmZkOWM5MTgzMGZmZTYzODRmODYxIiwiaWF0IjoxNjM3NTYwMjc5fQ.lenoAFcXxRT5neWf7mMEoKSL7Otdpus5lDHRtBkJtdA

{
  "title": "Testblog22",
  "author": "Author Veinti",
  "url": "https://someotherurl.com"
}
