PUT http://localhost:3003/api/blogs/616e897fd227c77b537f13fd
Content-Type: application/json

{
  "title": "Testblog20",
  "author": "Author Cinco",
  "url": "https://someotherurl.com",
  "likes": 10
}
